// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM4fO7WRSADws2tXO-o01Je-MPSSgw3_I',
    appId: '1:842240203166:web:b4e2fc6c23eb67af309e8f',
    messagingSenderId: '842240203166',
    projectId: 'scan-pay-cb590',
    authDomain: 'scan-pay-cb590.firebaseapp.com',
    databaseURL: 'https://scan-pay-cb590-default-rtdb.firebaseio.com',
    storageBucket: 'scan-pay-cb590.firebasestorage.app',
    measurementId: 'G-MPRT62PV17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0unXOCgRrwE4RL5oVKJGwzQOMTzmbjFo',
    appId: '1:842240203166:android:fe2871bf099041eb309e8f',
    messagingSenderId: '842240203166',
    projectId: 'scan-pay-cb590',
    databaseURL: 'https://scan-pay-cb590-default-rtdb.firebaseio.com',
    storageBucket: 'scan-pay-cb590.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWauvTNxh_QbwtFdNNivrZt2XBR87SpuE',
    appId: '1:842240203166:ios:f4ebe3b9356de840309e8f',
    messagingSenderId: '842240203166',
    projectId: 'scan-pay-cb590',
    databaseURL: 'https://scan-pay-cb590-default-rtdb.firebaseio.com',
    storageBucket: 'scan-pay-cb590.firebasestorage.app',
    iosClientId: '842240203166-jj9bpsj4thmddrdlr3u7hnco2vr05d8t.apps.googleusercontent.com',
    iosBundleId: 'com.example.scanPay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWauvTNxh_QbwtFdNNivrZt2XBR87SpuE',
    appId: '1:842240203166:ios:f4ebe3b9356de840309e8f',
    messagingSenderId: '842240203166',
    projectId: 'scan-pay-cb590',
    databaseURL: 'https://scan-pay-cb590-default-rtdb.firebaseio.com',
    storageBucket: 'scan-pay-cb590.firebasestorage.app',
    iosClientId: '842240203166-jj9bpsj4thmddrdlr3u7hnco2vr05d8t.apps.googleusercontent.com',
    iosBundleId: 'com.example.scanPay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM4fO7WRSADws2tXO-o01Je-MPSSgw3_I',
    appId: '1:842240203166:web:6f8c29fc292e1b99309e8f',
    messagingSenderId: '842240203166',
    projectId: 'scan-pay-cb590',
    authDomain: 'scan-pay-cb590.firebaseapp.com',
    databaseURL: 'https://scan-pay-cb590-default-rtdb.firebaseio.com',
    storageBucket: 'scan-pay-cb590.firebasestorage.app',
    measurementId: 'G-KP67BZRTJH',
  );
}
